logging:
  level:
    root: info
    com.gwm.one: debug
  file: logs/${spring.application.name}.log
spring:
  redis:
    host: @ipAddress@
    port: @redis-port@
    password: @redis-password@
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
      driver-class-name: @jdbcDriverClassName@
      url: @cloudNotificationUrl@
      username: @jdbcUsername@
      password: @jdbcPassword@
      hikari:
        minimum-idle: @hikari-minimum-idle@
        maximum-pool-size: @hikari-maximum-pool-size@
        connection-test-query: @hikari-connection-test-query@
  rabbitmq:
      host: @ipAddress@
      port: @mq-port@
      username: @mq-username@
      password: @mq-password@
      virtual-host: @mq-virtual-host@
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: @zipkin-base-url@
    enabled: @zipkin-enabled@
    sender:
      type: web
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka-url-test@
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.gwm.one.notification.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
mybatis-plus:
  mapperLocations: classpath:/mybatis-mappers/*
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gwm.one.notification.model
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_null
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    jdbc-type-for-null: 'null'
security:
  oauth2:
    resource:
      user-info-uri: @oauth2-user-info-uri@
      prefer-token-info: @oauth2-prefer-token-info@
aliyun:
  accessKeyId: @aliyun-accessKeyId@
  accessKeySecret: @aliyun-accessKeySecret@
  sign:
    name1: @aliyun-sign-name1@
  template:
    code1: @aliyun-template-code1@
sms:
  expire-minute: @sms-expire-minute@
  day-count: @sms-day-count@
testFlag: @testFlag@