logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  redis:
    host: @ipAddress@
    port: @redis-port@
    password: @redis-password@
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
      driver-class-name: @jdbcDriverClassName@
      url: @cloudNotificationUrl@
      username: @jdbcUsername@
      password: @jdbcPassword@
      hikari:
        minimum-idle: @hikari-minimum-idle@
        maximum-pool-size: @hikari-maximum-pool-size@
        connection-test-query: @hikari-connection-test-query@
  rabbitmq:
      host: @ipAddress@
      port: @mq-port@
      username: @mq-username@
      password: @mq-password@
      virtual-host: @mq-virtual-host@
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: @zipkin-base-url@
    enabled: @zipkin-enabled@
    sender:
      type: web
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka-url-test@
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.cloud.notification.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: @oauth2-user-info-uri@
      prefer-token-info: @oauth2-prefer-token-info@
aliyun:
  accessKeyId: @aliyun-accessKeyId@
  accessKeySecret: @aliyun-accessKeySecret@
  sign:
    name1: @aliyun-sign-name1@
  template:
    code1: @aliyun-template-code1@
sms:
  expire-minute: @sms-expire-minute@
  day-count: @sms-day-count@
testFlag: @testFlag@